version: '3'
services:
  web:
    build: ~/efc_test/weatherapp/frontend/
    command: npm start    
    ports:
      - "8000:8000"
    depends_on:
      - nodejs
  nodejs:
    build: ~/efc_test/weatherapp/backend/
    command: npm start
    ports:
      - "9000:9000"
